//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBM.Business.Model.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class admin_softbbmEntities : DbContext
    {
        public admin_softbbmEntities()
            : base("name=babymart_vnEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<admin_role> admin_role { get; set; }
        public virtual DbSet<cart> carts { get; set; }
        public virtual DbSet<donhang> donhangs { get; set; }
        public virtual DbSet<donhang_chuyenphat_danhsachdiachifuta> donhang_chuyenphat_danhsachdiachifuta { get; set; }
        public virtual DbSet<donhang_chuyenphat_tp_tinhtra> donhang_chuyenphat_tp_tinhtra { get; set; }
        public virtual DbSet<donhang_ct> donhang_ct { get; set; }
        public virtual DbSet<donhang_gio_giaohang> donhang_gio_giaohang { get; set; }
        public virtual DbSet<donhang_chuyenphat_tinh> donhang_chuyenphat_tinh { get; set; }
        public virtual DbSet<donhang_chuyenphat_tp> donhang_chuyenphat_tp { get; set; }
        public virtual DbSet<donhang_chuyenphat_vung> donhang_chuyenphat_vung { get; set; }
        public virtual DbSet<khachhang> khachhangs { get; set; }
        public virtual DbSet<khachhang_lienhe> khachhang_lienhe { get; set; }
        public virtual DbSet<khachhang_vanglai> khachhang_vanglai { get; set; }
        public virtual DbSet<module_detail> module_detail { get; set; }
        public virtual DbSet<module_group> module_group { get; set; }
        public virtual DbSet<module_menu> module_menu { get; set; }
        public virtual DbSet<shop_danhmuc_group> shop_danhmuc_group { get; set; }
        public virtual DbSet<shop_page> shop_page { get; set; }
        public virtual DbSet<shop_plan_saleoff> shop_plan_saleoff { get; set; }
        public virtual DbSet<shop_plan_type> shop_plan_type { get; set; }
        public virtual DbSet<shop_showhome> shop_showhome { get; set; }
        public virtual DbSet<shop_bienthe> shop_bienthe { get; set; }
        public virtual DbSet<shop_collection> shop_collection { get; set; }
        public virtual DbSet<shop_danhmuc> shop_danhmuc { get; set; }
        public virtual DbSet<shop_danhmuccon> shop_danhmuccon { get; set; }
        public virtual DbSet<shop_image> shop_image { get; set; }
        public virtual DbSet<shop_loai> shop_loai { get; set; }
        public virtual DbSet<shop_phanloai_dotuoi> shop_phanloai_dotuoi { get; set; }
        public virtual DbSet<shop_rightcol> shop_rightcol { get; set; }
        public virtual DbSet<shop_sanpham> shop_sanpham { get; set; }
        public virtual DbSet<shop_thuonghieu> shop_thuonghieu { get; set; }
        public virtual DbSet<soft_Branches> soft_Branches { get; set; }
        public virtual DbSet<soft_Branches_Product_Stock> soft_Branches_Product_Stock { get; set; }
        public virtual DbSet<soft_Catalog> soft_Catalog { get; set; }
        public virtual DbSet<soft_Channel> soft_Channel { get; set; }
        public virtual DbSet<soft_Channel_Product_Price> soft_Channel_Product_Price { get; set; }
        public virtual DbSet<soft_Channel_Product_SaleTotal> soft_Channel_Product_SaleTotal { get; set; }
        public virtual DbSet<soft_Config> soft_Config { get; set; }
        public virtual DbSet<soft_Config_PrintTem> soft_Config_PrintTem { get; set; }
        public virtual DbSet<soft_Discount> soft_Discount { get; set; }
        public virtual DbSet<soft_Employee_Title> soft_Employee_Title { get; set; }
        public virtual DbSet<soft_Notification> soft_Notification { get; set; }
        public virtual DbSet<soft_Order> soft_Order { get; set; }
        public virtual DbSet<soft_Order_Child> soft_Order_Child { get; set; }
        public virtual DbSet<soft_Suppliers> soft_Suppliers { get; set; }
        public virtual DbSet<soft_Unit> soft_Unit { get; set; }
        public virtual DbSet<support_cauhoi> support_cauhoi { get; set; }
        public virtual DbSet<support_feedback> support_feedback { get; set; }
        public virtual DbSet<support_silder> support_silder { get; set; }
        public virtual DbSet<support_textlink> support_textlink { get; set; }
        public virtual DbSet<sys_Banner> sys_Banner { get; set; }
        public virtual DbSet<sys_content> sys_content { get; set; }
        public virtual DbSet<sys_Employee> sys_Employee { get; set; }
        public virtual DbSet<sys_mail> sys_mail { get; set; }
        public virtual DbSet<sys_tags_Ref> sys_tags_Ref { get; set; }
        public virtual DbSet<sys_tags_Summary> sys_tags_Summary { get; set; }
        public virtual DbSet<sys_account_admin> sys_account_admin { get; set; }
        public virtual DbSet<sys_bangtin_conhang> sys_bangtin_conhang { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<sys_file> sys_file { get; set; }
        public virtual DbSet<sys_imagetype> sys_imagetype { get; set; }
        public virtual DbSet<sys_nhanbangtin> sys_nhanbangtin { get; set; }
    }
}
