//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBM.Business.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_sanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public shop_sanpham()
        {
            this.shop_bienthe = new HashSet<shop_bienthe>();
            this.shop_collection = new HashSet<shop_collection>();
            this.shop_image = new HashSet<shop_image>();
            this.sys_bangtin_conhang = new HashSet<sys_bangtin_conhang>();
            this.support_cauhoi = new HashSet<support_cauhoi>();
            this.soft_Branches_Product_Stock = new HashSet<soft_Branches_Product_Stock>();
            this.soft_Channel_Product_Price = new HashSet<soft_Channel_Product_Price>();
            this.soft_Order_Child = new HashSet<soft_Order_Child>();
        }
    
        public int id { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string masp { get; set; }
        public Nullable<int> maloai { get; set; }
        public Nullable<int> mahieu { get; set; }
        public Nullable<int> plantype { get; set; }
        public string tensp { get; set; }
        public string tensp_us { get; set; }
        public Nullable<int> typeshowhome { get; set; }
        public string thongtin { get; set; }
        public string thongtin_us { get; set; }
        public string spurl { get; set; }
        public string spurl_us { get; set; }
        public string sptitle { get; set; }
        public string sptitle_us { get; set; }
        public string spdescription { get; set; }
        public string spdescription_us { get; set; }
        public string spkeywords_us { get; set; }
        public string spkeywords { get; set; }
        public Nullable<bool> hide { get; set; }
        public string chitiet { get; set; }
        public string chitiet_us { get; set; }
        public Nullable<int> douutien { get; set; }
        public Nullable<bool> ischeckout { get; set; }
        public Nullable<bool> ischecksaleoff { get; set; }
        public Nullable<bool> ischeckgift { get; set; }
        public string gift { get; set; }
        public Nullable<int> countsale { get; set; }
        public Nullable<System.DateTime> timeend { get; set; }
        public Nullable<double> kg { get; set; }
        public Nullable<double> chieudai { get; set; }
        public Nullable<double> chieurong { get; set; }
        public Nullable<double> chieucao { get; set; }
        public Nullable<double> chieudaisd { get; set; }
        public Nullable<double> chieurongsd { get; set; }
        public Nullable<double> chieucaosd { get; set; }
        public Nullable<bool> showkg { get; set; }
        public Nullable<bool> showcm { get; set; }
        public Nullable<bool> showhome { get; set; }
        public Nullable<bool> showbanner { get; set; }
        public Nullable<bool> showsptangkemvaomuckm { get; set; }
        public Nullable<int> SuppliersId { get; set; }
        public Nullable<int> CatalogId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public string Barcode { get; set; }
        public Nullable<bool> Stop_Sale { get; set; }
        public Nullable<int> PriceBase { get; set; }
        public Nullable<int> PriceBase_Old { get; set; }
        public Nullable<int> PriceInput { get; set; }
        public Nullable<int> PriceCompare { get; set; }
        public Nullable<int> PriceWholesale { get; set; }
        public Nullable<bool> freeship { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> StatusVAT { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<int> FromCreate { get; set; }
    
        public virtual shop_showhome shop_showhome { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shop_bienthe> shop_bienthe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shop_collection> shop_collection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shop_image> shop_image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_bangtin_conhang> sys_bangtin_conhang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<support_cauhoi> support_cauhoi { get; set; }
        public virtual soft_Catalog soft_Catalog { get; set; }
        public virtual soft_Suppliers soft_Suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<soft_Branches_Product_Stock> soft_Branches_Product_Stock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<soft_Channel_Product_Price> soft_Channel_Product_Price { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<soft_Order_Child> soft_Order_Child { get; set; }
        public virtual shop_thuonghieu shop_thuonghieu { get; set; }
    }
}
