//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBM.Business.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class soft_Channel_Product_Price
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public soft_Channel_Product_Price()
        {
            this.soft_Channel_Product_SaleTotal = new HashSet<soft_Channel_Product_SaleTotal>();
        }
    
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int ChannelId { get; set; }
        public int Price { get; set; }
        public Nullable<int> Price_Discount { get; set; }
        public Nullable<System.DateTime> StartDate_Discount { get; set; }
        public Nullable<System.DateTime> Enddate_Discount { get; set; }
        public string Note { get; set; }
        public int EmployeeCreate { get; set; }
        public System.DateTime DateCreate { get; set; }
        public Nullable<int> EmployeeUpdate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
    
        public virtual shop_sanpham shop_sanpham { get; set; }
        public virtual soft_Channel soft_Channel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<soft_Channel_Product_SaleTotal> soft_Channel_Product_SaleTotal { get; set; }
    }
}
