//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBM.Business.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class soft_Order_Child
    {
        public long Id { get; set; }
        public long OrderId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual shop_sanpham shop_sanpham { get; set; }
        public virtual soft_Order soft_Order { get; set; }
    }
}
