//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBM.Business.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class soft_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public soft_Order()
        {
            this.soft_Order_Child = new HashSet<soft_Order_Child>();
        }
    
        public long Id { get; set; }
        public Nullable<int> Channeld { get; set; }
        public string Code { get; set; }
        public Nullable<int> Id_Customer { get; set; }
        public Nullable<int> Id_From { get; set; }
        public Nullable<int> Id_To { get; set; }
        public int Status { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> TotalOrther { get; set; }
        public string Note { get; set; }
        public Nullable<int> TypeOrder { get; set; }
        public Nullable<bool> IsShip { get; set; }
        public string DisscountCode { get; set; }
        public Nullable<int> DisscountValue { get; set; }
        public Nullable<int> EmployeeShip { get; set; }
        public int EmployeeCreate { get; set; }
        public System.DateTime DateCreate { get; set; }
        public Nullable<int> EmployeeUpdate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
    
        public virtual khachhang khachhang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<soft_Order_Child> soft_Order_Child { get; set; }
    }
}
