//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBM.Business.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class soft_Config_PrintTem
    {
        public int Id { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string Tmp { get; set; }
        public Nullable<int> MarginLeftPage { get; set; }
        public Nullable<int> MarginLeftItem { get; set; }
        public Nullable<int> HeightItem { get; set; }
        public Nullable<int> WidthItem { get; set; }
        public Nullable<int> HeightFlag { get; set; }
        public Nullable<int> WidthFlag { get; set; }
        public Nullable<int> PageSize { get; set; }
        public Nullable<int> ItemInLine { get; set; }
        public Nullable<int> FontSize { get; set; }
        public Nullable<int> PaddingItem { get; set; }
        public Nullable<int> PaddingTopPage { get; set; }
        public int PaddingBotPage { get; set; }
        public Nullable<int> PaddingLeftPage { get; set; }
        public Nullable<int> PaddingRightPage { get; set; }
        public Nullable<int> MarginBottomItem { get; set; }
    }
}
