//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBM.Business.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class soft_Notification
    {
        public int Id { get; set; }
        public string Contents { get; set; }
        public Nullable<int> Ref { get; set; }
        public string Href { get; set; }
        public Nullable<int> Branch { get; set; }
        public Nullable<int> Channel { get; set; }
        public Nullable<int> UserId { get; set; }
        public int Type { get; set; }
        public bool IsReview { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
    }
}
