//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBM.Business.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class soft_Config
    {
        public int Id { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Braches { get; set; }
        public bool Is_import { get; set; }
        public string Error_Import { get; set; }
        public Nullable<int> Percent_Process { get; set; }
    }
}
